version: '3.9'
services:
  configserver:
    image: mongo:6.0
    container_name: mongo-config-server
    command: mongod --configsvr --replSet configReplSet --port 27019 --bind_ip_all
    ports:
      - "27019:27019"
    volumes:
      - ./config-server:/data/db
    networks:
      - mongo-network

  shard1:
    image: mongo:6.0
    container_name: mongo-shard1
    command: mongod --shardsvr --replSet shard1ReplSet --port 27021 --bind_ip_all
    ports:
      - "27021:27021"
    volumes:
      - ./shard1:/data/db
    networks:
      - mongo-network

  shard2:
    image: mongo:6.0
    container_name: mongo-shard2
    command: mongod --shardsvr --replSet shard2ReplSet --port 27022 --bind_ip_all
    ports:
      - "27022:27022"
    volumes:
      - ./shard2:/data/db
    networks:
      - mongo-network

  shard3:
    image: mongo:6.0
    container_name: mongo-shard3
    command: mongod --shardsvr --replSet shard3ReplSet --port 27023 --bind_ip_all
    ports:
      - "27023:27023"
    volumes:
      - ./shard3:/data/db
    networks:
      - mongo-network

  mongos:
    image: mongo:6.0
    container_name: mongo-router
    command: mongos --configdb configReplSet/mongo-config-server:27019 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - configserver
      - shard1
      - shard2
      - shard3
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
